# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore --configuration Release 

    - name: Create .adventofcode.session file
      env:
        AOC_SESSION: ${{ secrets.AOC_SESSION }}
      run: echo "$AOC_SESSION" > .adventofcode.session

    - name: Read Cache Inputs
      uses: actions/cache@v4
      with:
        key: session-${{ hashFiles('.adventofcode.session') }}
        path: 
          '**/inputs/**'

    - name: Hash inputs
      id: input-hash
      env:
        INPUT_HASH: ${{ hashFiles('**/inputs/**') }}
      run:
        echo "INPUT_HASH=$INPUT_HASH" >> $GITHUB_OUTPUT
    
    - name: Run tests
      run: dotnet run --configuration Release --no-build -- test *:*

    - name: Write Cache
      uses: actions/cache/save@v4
      if: always() && hashFiles('**/inputs/**') != steps.input-hash.outputs.INPUT_HASH
      with:
        key: session-${{ hashFiles('.adventofcode.session') }}
        path: 
          '**/inputs/**'


